### PR TITLE
Fix include path.

### PR DESCRIPTION
**Pull request by Stebalien**

### CODE REVIEW

**Comment by niklata** [comment]
ncmlib isn't meant to be built as a standalone library; it's always included as part of another project (in a subdirectory) and statically linked.

I'm looking at a solution for the older ndyndns now; most likely I'll just create a stable branch for the old google code version and just patch it minimally to build against the current ncmlib.

**Comment by niklata** [comment]
What I will do is tag d493a481a96725d66 as 2.3 as the legacy branch with dyn.com support.  This revision still has the old ncmlib internal to the legacy ndyndns and still has dyn.com support, so it trivially compiles and works.  Then I will update ndyndns master to the current version that I run locally that no longer supports dyn.com, which works with the current ncmlib code.

Hopefully this will be a clean solution.  I've tested by pulling from github and building d493a481a96725d66 and it compiles cleanly for me.

Using the latest ncmlib will require a fair bit of integration changes, as I migrated completely away from strlcpy/strlcat to snprintf, among other things, and the old code was removed, so I don't want to go down that path for a stable version.

**Comment by niklata** [comment]
And since I migrated the github project from google code rather than pushing from my local repo, the sha1 tree is different.  I will delete the github copy, tag a legacy branch in my local repo from the equivalent commit, push my local repo to github, and tag a release version of 2.3.

**Comment by Stebalien** [comment]
Thanks.

**Pull request closed without merging**
